name: test

on:
  workflow_dispatch:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
