name: Call API Example

on:
  workflow_dispatch:
    inputs:
      npmtoken:
        required: true
        type: string

jobs:
  do_the_thing:
    runs-on: ubuntu-latest
    steps:
    - name: Mask Password
      run: |
        NPM_TOKEN=$(jq -r '.inputs.npmtoken' $GITHUB_EVENT_PATH)
        echo ::add-mask::$NPM_TOKEN
        echo NPM_TOKEN=$NPM_TOKEN >> $GITHUB_ENV
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
