name: test

on:
  workflow_dispatch:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  my_first_job:
    name: My first job
