name: NPM publish

on:
  workflow_dispatch:
    inputs:
      nodeauthtoken:
        required: true
        type: string

jobs:
  test_publish_npm:
    runs-on: ubuntu-latest
    steps:
    - name: Mask Password
      run: |
        NODE_AUTH_TOKEN=$(jq -r '.inputs.nodeauthtoken' $GITHUB_EVENT_PATH)
        echo ::add-mask::$NODE_AUTH_TOKEN
        echo NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN >> $GITHUB_ENV
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
