name: Call API Example

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
      password:
        required: true
        type: string

jobs:
  do_the_thing:
    runs-on: ubuntu-latest
    steps:
    #- name: Mask Password
    #  run: |
    #    API_PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
    #    echo ::add-mask::$API_PASSWORD
    #    echo API_PASSWORD=$API_PASSWORD >> $GITHUB_ENV
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ github.event.inputs.password }}
